import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Card } from "@/components/ui/card";
import { MessageSquare, Send, Sparkles, Loader2, User, Bot, Trash2 } from "lucide-react";
import { useState, useRef, useEffect, useMemo } from "react";
import { toast } from "sonner";
import ReactMarkdown from "react-markdown";

type ChatMessage = { role:"user"|"assistant"; content:string; timestamp:Date };
export default function Assistente(){
 const[messages,setMessages]=useState<ChatMessage[]>([]);const[input,setInput]=useState("");const[selectedCondo,setSelectedCondo]=useState("");const scrollRef=useRef<HTMLDivElement>(null);const inputRef=useRef<HTMLInputElement>(null);
 const{data:condos}=trpc.condominium.list.useQuery();
 const chatMutation=trpc.ai.chat.useMutation({onSuccess:r=>setMessages(p=>[...p,{role:"assistant",content:r.content,timestamp:new Date()}]),onError:()=>{toast.error("Erro ao consultar o assistente");setMessages(p=>[...p,{role:"assistant",content:"Desculpe, ocorreu um erro. Tente novamente.",timestamp:new Date()}])}});
 useEffect(()=>{if(scrollRef.current)scrollRef.current.scrollTop=scrollRef.current.scrollHeight},[messages]);
 const handleSend=()=>{if(!input.trim())return;setMessages(p=>[...p,{role:"user",content:input.trim(),timestamp:new Date()}]);chatMutation.mutate({message:input.trim(),condominiumId:selectedCondo&&selectedCondo!=="all"?parseInt(selectedCondo):undefined});setInput("");inputRef.current?.focus()};
 const handleKeyDown=(e:React.KeyboardEvent)=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();handleSend()}};
 const condoName=useMemo(()=>!selectedCondo||!condos?null:condos.find((c:any)=>c.id===parseInt(selectedCondo))?.name,[selectedCondo,condos]);
 return <div className="flex flex-col h-[calc(100vh-6rem)] md:h-[calc(100vh-4rem)]"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4"><div><h1 className="text-2xl font-bold tracking-tight flex items-center gap-2"><Sparkles className="h-6 w-6 text-primary"/>Assistente IA</h1><p className="text-muted-foreground text-sm">Consulte regras, convenções e tire dúvidas jurídicas</p></div><div className="flex items-center gap-2"><Select value={selectedCondo} onValueChange={setSelectedCondo}><SelectTrigger className="w-56"><SelectValue placeholder="Contexto: Todos os condomínios"/></SelectTrigger><SelectContent><SelectItem value="all">Todos os condomínios</SelectItem>{condos?.map((c:any)=><SelectItem key={c.id} value={c.id.toString()}>{c.name}</SelectItem>)}</SelectContent></Select>{messages.length>0&&<Button variant="ghost" size="icon" onClick={()=>setMessages([])} className="text-muted-foreground"><Trash2 className="h-4 w-4"/></Button>}</div></div>
 <Card className="flex-1 border-0 shadow-sm flex flex-col overflow-hidden"><ScrollArea className="flex-1 p-4" ref={scrollRef}>{messages.length===0?<div className="flex flex-col items-center justify-center h-full text-center py-16"><div className="h-16 w-16 rounded-2xl bg-primary/10 flex items-center justify-center mb-4"><MessageSquare className="h-8 w-8 text-primary"/></div><h3 className="font-semibold text-lg mb-2">Como posso ajudar?</h3><p className="text-muted-foreground text-sm max-w-md mb-6">Pergunte sobre regras do condomínio, legislação condominial, procedimentos legais ou peça ajuda para redigir documentos.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-w-lg">{["Quais são as regras sobre barulho após 22h?","Como aplicar uma multa por infração?","Qual o prazo para convocar assembleia?","Quais documentos preciso para renovar o AVCB?"].map(s=><Button key={s} variant="outline" className="h-auto py-3 px-4 text-left text-xs justify-start whitespace-normal" onClick={()=>{setInput(s);inputRef.current?.focus()}}>{s}</Button>)}</div></div>:<div className="space-y-4">{messages.map((msg,i)=><div key={i} className={`flex gap-3 ${msg.role==="user"?"justify-end":"justify-start"}`}>{msg.role==="assistant"&&<div className="h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 mt-1"><Bot className="h-4 w-4 text-primary"/></div>}<div className={`max-w-[80%] rounded-2xl px-4 py-3 ${msg.role==="user"?"bg-primary text-primary-foreground":"bg-muted"}`}>{msg.role==="assistant"?<div className="prose prose-sm max-w-none text-foreground"><ReactMarkdown>{msg.content}</ReactMarkdown></div>:<p className="text-sm">{msg.content}</p>}</div>{msg.role==="user"&&<div className="h-8 w-8 rounded-lg bg-secondary flex items-center justify-center shrink-0 mt-1"><User className="h-4 w-4"/></div>}</div>)}{chatMutation.isPending&&<div className="flex gap-3"><div className="h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0"><Bot className="h-4 w-4 text-primary"/></div><div className="bg-muted rounded-2xl px-4 py-3"><Loader2 className="h-4 w-4 animate-spin text-muted-foreground"/></div></div>}</div>}</ScrollArea><div className="border-t p-4">{condoName&&<p className="text-xs text-muted-foreground mb-2">Contexto: <span className="font-medium">{condoName}</span></p>}<div className="flex gap-2"><Input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={handleKeyDown} placeholder="Digite sua pergunta..." disabled={chatMutation.isPending} className="flex-1"/><Button onClick={handleSend} disabled={!input.trim()||chatMutation.isPending} size="icon"><Send className="h-4 w-4"/></Button></div></div></Card></div>;
}
