-- SindCopilot independente — Supabase/Postgres
create extension if not exists vector;
create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  phone text,
  cpf text,
  creci text,
  company text,
  role text not null default 'user' check (role in ('user','admin')),
  plan text not null default 'free' check (plan in ('free','starter','pro','scale')),
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  stripe_status text,
  stripe_current_period_end timestamptz,
  trial_ends_at timestamptz not null default (now() + interval '7 days'),
  account_owner_id uuid references public.users(id) on delete set null,
  account_role text not null default 'owner' check (account_role in ('owner','assistant','viewer')),
  lgpd_consent_at timestamptz,
  lgpd_consent_version text,
  terms_accepted_at timestamptz,
  profile_completed boolean not null default false,
  storage_bytes bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);
drop trigger if exists users_updated_at on public.users;
create trigger users_updated_at before update on public.users for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.users (
    id, email, name, terms_accepted_at, lgpd_consent_at, lgpd_consent_version
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(coalesce(new.email,''), '@', 1)),
    case when new.raw_user_meta_data->>'accepted_terms' = 'true' then now() else null end,
    case when new.raw_user_meta_data->>'accepted_terms' = 'true' then now() else null end,
    case when new.raw_user_meta_data->>'accepted_terms' = 'true' then coalesce(new.raw_user_meta_data->>'lgpd_version','1.0') else null end
  )
  on conflict (id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();

create table if not exists public.assistants (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.users(id) on delete cascade,
  email text not null,
  name text,
  phone text,
  status text not null default 'pending' check (status in ('pending','active','revoked')),
  invite_token text not null unique,
  user_id uuid references public.users(id) on delete set null,
  role text not null default 'assistant' check (role in ('assistant','viewer')),
  allowed_condominium_ids bigint[] null,
  expires_at timestamptz not null default (now() + interval '7 days'),
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id, email)
);
create index if not exists assistants_owner_idx on public.assistants(owner_id);
create index if not exists assistants_user_idx on public.assistants(user_id);
drop trigger if exists assistants_updated_at on public.assistants;
create trigger assistants_updated_at before update on public.assistants for each row execute function public.set_updated_at();

create table if not exists public.condominiums (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  cnpj text,
  address text,
  city text,
  state text,
  zip_code text,
  phone text,
  email text,
  status text not null default 'active' check (status in ('active','inactive')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists condominiums_user_idx on public.condominiums(user_id);
drop trigger if exists condominiums_updated_at on public.condominiums;
create trigger condominiums_updated_at before update on public.condominiums for each row execute function public.set_updated_at();

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  number text not null,
  block text,
  floor text,
  owner_name text,
  owner_phone text,
  owner_email text,
  resident_name text,
  resident_phone text,
  resident_email text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(condominium_id, number, block)
);
create index if not exists units_condominium_idx on public.units(condominium_id);
drop trigger if exists units_updated_at on public.units;
create trigger units_updated_at before update on public.units for each row execute function public.set_updated_at();

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null check (type in ('nota_fiscal','recibo','ordem_servico','boleto','ata','convencao','regimento','contrato','laudo','outro')),
  title text,
  description text,
  file_key text not null unique,
  file_name text,
  mime_type text,
  size_bytes bigint not null default 0,
  ocr_supplier_name text,
  ocr_supplier_cnpj text,
  ocr_value_cents bigint,
  ocr_date date,
  ocr_category text,
  ocr_summary text,
  ocr_status text not null default 'pending' check (ocr_status in ('pending','processing','completed','failed','not_required')),
  indexing_status text not null default 'not_required' check (indexing_status in ('pending','processing','completed','failed','not_required')),
  indexing_error text,
  text_content text,
  page_count integer,
  year integer,
  month integer,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists documents_user_idx on public.documents(user_id);
create index if not exists documents_condominium_idx on public.documents(condominium_id);
create index if not exists documents_type_idx on public.documents(type);
drop trigger if exists documents_updated_at on public.documents;
create trigger documents_updated_at before update on public.documents for each row execute function public.set_updated_at();

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.documents(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  page_number integer,
  chunk_index integer not null,
  content text not null,
  embedding vector(1536) not null,
  created_at timestamptz not null default now(),
  unique(document_id, chunk_index)
);
create index if not exists chunks_document_idx on public.document_chunks(document_id);
create index if not exists chunks_condominium_idx on public.document_chunks(condominium_id);
create index if not exists chunks_embedding_idx on public.document_chunks using ivfflat (embedding vector_cosine_ops) with (lists = 100);

create table if not exists public.obligations (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  description text,
  category text not null check (category in ('avcb','seguro','dedetizacao','caixa_dagua','para_raios','elevador','extintores','laudo_eletrico','laudo_estrutural','outro')),
  due_date timestamptz not null,
  alert_days_before integer not null default 30 check (alert_days_before between 0 and 365),
  is_recurring boolean not null default false,
  recurring_months integer check (recurring_months is null or recurring_months between 1 and 120),
  status text not null default 'pending' check (status in ('pending','upcoming','overdue','completed')),
  completed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists obligations_user_due_idx on public.obligations(user_id, due_date);
create index if not exists obligations_condominium_idx on public.obligations(condominium_id);
drop trigger if exists obligations_updated_at on public.obligations;
create trigger obligations_updated_at before update on public.obligations for each row execute function public.set_updated_at();

create table if not exists public.compliance_alerts (
  id bigint generated by default as identity primary key,
  obligation_id bigint not null references public.obligations(id) on delete cascade,
  due_date timestamptz not null,
  alert_key text not null,
  recipient text,
  delivery_status text not null default 'pending' check (delivery_status in ('pending','sent','failed','skipped')),
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique(obligation_id, due_date, alert_key)
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  unit_id bigint references public.units(id) on delete set null,
  type text not null check (type in ('notificacao','multa','comunicado','advertencia')),
  subject text not null,
  description text,
  generated_content text,
  legal_basis text,
  source_refs jsonb not null default '[]'::jsonb,
  warning text,
  status text not null default 'draft' check (status in ('draft','sent','cancelled')),
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists notices_user_idx on public.notices(user_id);
create index if not exists notices_condominium_idx on public.notices(condominium_id);
drop trigger if exists notices_updated_at on public.notices;
create trigger notices_updated_at before update on public.notices for each row execute function public.set_updated_at();

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  cnpj text,
  category text,
  phone text,
  email text,
  address text,
  rating integer check (rating is null or rating between 1 and 5),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists suppliers_user_idx on public.suppliers(user_id);
drop trigger if exists suppliers_updated_at on public.suppliers;
create trigger suppliers_updated_at before update on public.suppliers for each row execute function public.set_updated_at();

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  condominium_id bigint references public.condominiums(id) on delete cascade,
  actor_user_id uuid references public.users(id) on delete set null,
  role text not null check (role in ('user','assistant','system')),
  content text not null,
  citations jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists chat_user_condo_idx on public.chat_messages(user_id, condominium_id, created_at desc);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  actor_user_id uuid references public.users(id) on delete set null,
  condominium_id bigint references public.condominiums(id) on delete cascade,
  type text not null,
  title text not null,
  description text,
  created_at timestamptz not null default now()
);
create index if not exists activities_user_idx on public.activities(user_id, created_at desc);

create table if not exists public.usage_monthly (
  user_id uuid not null references public.users(id) on delete cascade,
  period_start date not null,
  ocr_count integer not null default 0,
  ai_count integer not null default 0,
  notices_count integer not null default 0,
  storage_bytes bigint not null default 0,
  updated_at timestamptz not null default now(),
  primary key(user_id, period_start)
);

create table if not exists public.stripe_events (
  id text primary key,
  event_type text not null,
  payload jsonb,
  status text not null default 'processing' check (status in ('processing','processed','failed')),
  error_message text,
  processed_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.consume_monthly_usage(
  p_user_id uuid,
  p_metric text,
  p_limit integer,
  p_amount integer default 1
) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  v_period date := date_trunc('month', now())::date;
  v_current integer;
begin
  insert into public.usage_monthly(user_id, period_start)
  values (p_user_id, v_period)
  on conflict (user_id, period_start) do nothing;

  if p_metric = 'ocr' then
    select ocr_count into v_current from public.usage_monthly where user_id=p_user_id and period_start=v_period for update;
    if v_current + p_amount > p_limit then return false; end if;
    update public.usage_monthly set ocr_count=ocr_count+p_amount, updated_at=now() where user_id=p_user_id and period_start=v_period;
  elsif p_metric = 'ai' then
    select ai_count into v_current from public.usage_monthly where user_id=p_user_id and period_start=v_period for update;
    if v_current + p_amount > p_limit then return false; end if;
    update public.usage_monthly set ai_count=ai_count+p_amount, updated_at=now() where user_id=p_user_id and period_start=v_period;
  elsif p_metric = 'notices' then
    select notices_count into v_current from public.usage_monthly where user_id=p_user_id and period_start=v_period for update;
    if v_current + p_amount > p_limit then return false; end if;
    update public.usage_monthly set notices_count=notices_count+p_amount, updated_at=now() where user_id=p_user_id and period_start=v_period;
  else
    raise exception 'Métrica inválida';
  end if;
  return true;
end $$;

create or replace function public.reserve_storage(
  p_user_id uuid,
  p_limit_bytes bigint,
  p_amount_bytes bigint
) returns boolean
language plpgsql security definer set search_path = public as $$
declare v_current bigint;
begin
  select storage_bytes into v_current from public.users where id=p_user_id for update;
  if coalesce(v_current,0) + p_amount_bytes > p_limit_bytes then return false; end if;
  update public.users set storage_bytes=storage_bytes+p_amount_bytes where id=p_user_id;
  return true;
end $$;

create or replace function public.release_storage(p_user_id uuid, p_amount_bytes bigint)
returns void language sql security definer set search_path=public as $$
  update public.users
  set storage_bytes = greatest(0, storage_bytes - greatest(0, p_amount_bytes))
  where id=p_user_id;
$$;

create or replace function public.match_document_chunks(
  query_embedding vector(1536),
  match_user_id uuid,
  match_condominium_id bigint,
  match_count integer default 8
) returns table (
  id bigint,
  document_id bigint,
  title text,
  page_number integer,
  content text,
  similarity double precision
)
language sql stable as $$
  select dc.id, dc.document_id, d.title, dc.page_number, dc.content,
         1 - (dc.embedding <=> query_embedding) as similarity
  from public.document_chunks dc
  join public.documents d on d.id = dc.document_id
  where dc.user_id = match_user_id
    and dc.condominium_id = match_condominium_id
  order by dc.embedding <=> query_embedding
  limit match_count;
$$;

-- RLS: backend usa service role, mas estas políticas protegem acessos acidentais pelo cliente.
alter table public.users enable row level security;
alter table public.assistants enable row level security;
alter table public.condominiums enable row level security;
alter table public.units enable row level security;
alter table public.documents enable row level security;
alter table public.document_chunks enable row level security;
alter table public.obligations enable row level security;
alter table public.notices enable row level security;
alter table public.suppliers enable row level security;
alter table public.chat_messages enable row level security;
alter table public.activities enable row level security;
alter table public.usage_monthly enable row level security;
alter table public.compliance_alerts enable row level security;
alter table public.stripe_events enable row level security;

-- The browser uses Supabase only for Auth. Business data is available exclusively
-- through the server, which authenticates every request and uses the service role.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.consume_monthly_usage(uuid,text,integer,integer) from public, anon, authenticated;
revoke all on function public.reserve_storage(uuid,bigint,bigint) from public, anon, authenticated;
revoke all on function public.release_storage(uuid,bigint) from public, anon, authenticated;
revoke all on function public.match_document_chunks(vector,uuid,bigint,integer) from public, anon, authenticated;
grant execute on function public.consume_monthly_usage(uuid,text,integer,integer) to service_role;
grant execute on function public.reserve_storage(uuid,bigint,bigint) to service_role;
grant execute on function public.release_storage(uuid,bigint) to service_role;
grant execute on function public.match_document_chunks(vector,uuid,bigint,integer) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('documents','documents',false,20971520,array['application/pdf','image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=false, file_size_limit=20971520, allowed_mime_types=excluded.allowed_mime_types;
