-- SindCopilot — Ocorrências, evidências, linha do tempo e governança disciplinar

create table if not exists public.occurrences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  unit_id bigint references public.units(id) on delete set null,
  created_by uuid references public.users(id) on delete set null,
  title text not null,
  description text not null,
  category text not null check (category in ('barulho','obra','pet','garagem','area_comum','convivencia','seguranca','dano','financeiro','outro')),
  severity text not null default 'medium' check (severity in ('low','medium','high','urgent')),
  status text not null default 'open' check (status in ('open','under_review','notified','penalized','resolved','archived')),
  happened_at timestamptz not null default now(),
  location text,
  reported_by text,
  reported_channel text not null default 'manual' check (reported_channel in ('manual','portaria','email','whatsapp','visit','other')),
  source_type text not null default 'manual' check (source_type in ('manual','visit','system')),
  source_visit_id bigint references public.field_visits(id) on delete set null,
  source_item_client_id text,
  rule_document_id bigint references public.documents(id) on delete set null,
  rule_page integer,
  rule_reference text,
  rule_excerpt text,
  resolution text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists occurrences_user_created_idx on public.occurrences(user_id, created_at desc);
create index if not exists occurrences_condominium_idx on public.occurrences(condominium_id, status, happened_at desc);
create index if not exists occurrences_unit_idx on public.occurrences(unit_id, category, happened_at desc);
create index if not exists occurrences_source_visit_idx on public.occurrences(source_visit_id);
create unique index if not exists occurrences_visit_item_unique_idx
  on public.occurrences(source_visit_id, source_item_client_id)
  where source_visit_id is not null and source_item_client_id is not null;
drop trigger if exists occurrences_updated_at on public.occurrences;
create trigger occurrences_updated_at before update on public.occurrences for each row execute function public.set_updated_at();

create table if not exists public.occurrence_evidence (
  id bigint generated by default as identity primary key,
  occurrence_id bigint not null references public.occurrences(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  document_id bigint references public.documents(id) on delete set null,
  kind text not null check (kind in ('photo','video','audio','document','testimony','other')),
  description text,
  witness_name text,
  captured_at timestamptz,
  file_key text unique,
  file_name text,
  mime_type text,
  size_bytes bigint not null default 0,
  sha256 text,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists occurrence_evidence_occurrence_idx on public.occurrence_evidence(occurrence_id, created_at);

create table if not exists public.occurrence_events (
  id bigint generated by default as identity primary key,
  occurrence_id bigint not null references public.occurrences(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  actor_user_id uuid references public.users(id) on delete set null,
  type text not null check (type in ('created','note','evidence_added','defense_received','notice_created','notice_sent','penalty_applied','status_changed','resolved','reopened')),
  title text not null,
  description text,
  notice_id bigint references public.notices(id) on delete set null,
  document_id bigint references public.documents(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists occurrence_events_occurrence_idx on public.occurrence_events(occurrence_id, created_at);

alter table public.notices add column if not exists occurrence_id bigint references public.occurrences(id) on delete set null;
create index if not exists notices_occurrence_idx on public.notices(occurrence_id);

alter table public.occurrences enable row level security;
alter table public.occurrence_evidence enable row level security;
alter table public.occurrence_events enable row level security;

revoke all on public.occurrences from anon, authenticated;
revoke all on public.occurrence_evidence from anon, authenticated;
revoke all on public.occurrence_events from anon, authenticated;
revoke all on sequence public.occurrences_id_seq from anon, authenticated;
revoke all on sequence public.occurrence_evidence_id_seq from anon, authenticated;
revoke all on sequence public.occurrence_events_id_seq from anon, authenticated;

grant all on public.occurrences to service_role;
grant all on public.occurrence_evidence to service_role;
grant all on public.occurrence_events to service_role;
grant usage, select on sequence public.occurrences_id_seq to service_role;
grant usage, select on sequence public.occurrence_evidence_id_seq to service_role;
grant usage, select on sequence public.occurrence_events_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'occurrence-evidence',
  'occurrence-evidence',
  false,
  26214400,
  array[
    'application/pdf',
    'image/jpeg','image/png','image/webp',
    'video/mp4','video/webm',
    'audio/mpeg','audio/mp4','audio/webm','audio/wav','audio/ogg'
  ]
)
on conflict (id) do update
set public=false,
    file_size_limit=26214400,
    allowed_mime_types=excluded.allowed_mime_types;
