-- SindCopilot — Financeiro Inteligente multi-condomínio
-- Extratos, lançamentos auditáveis, regras de classificação, conciliação e fechamento mensal.

create table if not exists public.financial_statements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  uploaded_by uuid references public.users(id) on delete set null,
  file_key text unique,
  file_name text not null,
  mime_type text,
  size_bytes bigint not null default 0,
  sha256 text,
  source_format text not null check (source_format in ('csv','xlsx','ofx','pdf','manual')),
  bank_name text,
  account_name text,
  period_start date,
  period_end date,
  opening_balance numeric(16,2),
  bank_closing_balance numeric(16,2),
  calculated_closing_balance numeric(16,2),
  reconciliation_difference numeric(16,2),
  status text not null default 'imported' check (status in ('imported','review','reconciled','closed')),
  transaction_count integer not null default 0,
  raw_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists financial_statements_user_idx on public.financial_statements(user_id, created_at desc);
create index if not exists financial_statements_condo_idx on public.financial_statements(condominium_id, period_start desc, period_end desc);
drop trigger if exists financial_statements_updated_at on public.financial_statements;
create trigger financial_statements_updated_at before update on public.financial_statements for each row execute function public.set_updated_at();

create table if not exists public.financial_transactions (
  id bigint generated by default as identity primary key,
  statement_id bigint not null references public.financial_statements(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  posted_at date not null,
  description text not null,
  normalized_description text not null,
  amount numeric(16,2) not null check (amount <> 0),
  direction text not null check (direction in ('income','expense')),
  category text not null default 'A classificar',
  subcategory text,
  confidence numeric(5,4) not null default 0,
  classification_source text not null default 'system' check (classification_source in ('system','rule','ai','manual')),
  needs_review boolean not null default true,
  source_line integer,
  external_id text,
  fingerprint text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists financial_transactions_statement_idx on public.financial_transactions(statement_id, posted_at, id);
create index if not exists financial_transactions_condo_idx on public.financial_transactions(condominium_id, posted_at desc);
create index if not exists financial_transactions_review_idx on public.financial_transactions(condominium_id, needs_review, posted_at desc);
create index if not exists financial_transactions_description_idx on public.financial_transactions(user_id, normalized_description);
drop trigger if exists financial_transactions_updated_at on public.financial_transactions;
create trigger financial_transactions_updated_at before update on public.financial_transactions for each row execute function public.set_updated_at();

create table if not exists public.financial_category_rules (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  condominium_id bigint references public.condominiums(id) on delete cascade,
  pattern text not null,
  direction text check (direction in ('income','expense')),
  category text not null,
  subcategory text,
  active boolean not null default true,
  uses integer not null default 0,
  created_by uuid references public.users(id) on delete set null,
  last_used_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, condominium_id, pattern, direction)
);

create index if not exists financial_category_rules_owner_idx on public.financial_category_rules(user_id, condominium_id, active);
drop trigger if exists financial_category_rules_updated_at on public.financial_category_rules;
create trigger financial_category_rules_updated_at before update on public.financial_category_rules for each row execute function public.set_updated_at();

create table if not exists public.financial_closings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  condominium_id bigint not null references public.condominiums(id) on delete cascade,
  period_month date not null,
  statement_ids bigint[] not null default '{}',
  opening_balance numeric(16,2) not null default 0,
  income_total numeric(16,2) not null default 0,
  expense_total numeric(16,2) not null default 0,
  calculated_closing_balance numeric(16,2) not null default 0,
  bank_closing_balance numeric(16,2),
  reconciliation_difference numeric(16,2),
  status text not null default 'draft' check (status in ('draft','reconciled','closed')),
  notes text,
  closed_by uuid references public.users(id) on delete set null,
  closed_at timestamptz,
  last_exported_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, condominium_id, period_month)
);

create index if not exists financial_closings_condo_idx on public.financial_closings(condominium_id, period_month desc);
drop trigger if exists financial_closings_updated_at on public.financial_closings;
create trigger financial_closings_updated_at before update on public.financial_closings for each row execute function public.set_updated_at();

alter table public.financial_statements enable row level security;
alter table public.financial_transactions enable row level security;
alter table public.financial_category_rules enable row level security;
alter table public.financial_closings enable row level security;

revoke all on public.financial_statements from anon, authenticated;
revoke all on public.financial_transactions from anon, authenticated;
revoke all on public.financial_category_rules from anon, authenticated;
revoke all on public.financial_closings from anon, authenticated;
revoke all on sequence public.financial_statements_id_seq from anon, authenticated;
revoke all on sequence public.financial_transactions_id_seq from anon, authenticated;
revoke all on sequence public.financial_category_rules_id_seq from anon, authenticated;
revoke all on sequence public.financial_closings_id_seq from anon, authenticated;

grant all on public.financial_statements to service_role;
grant all on public.financial_transactions to service_role;
grant all on public.financial_category_rules to service_role;
grant all on public.financial_closings to service_role;
grant usage, select on sequence public.financial_statements_id_seq to service_role;
grant usage, select on sequence public.financial_transactions_id_seq to service_role;
grant usage, select on sequence public.financial_category_rules_id_seq to service_role;
grant usage, select on sequence public.financial_closings_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'finance-statements',
  'finance-statements',
  false,
  20971520,
  array[
    'text/csv','text/plain','application/csv',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-excel',
    'application/pdf',
    'application/x-ofx','application/ofx','application/octet-stream'
  ]
)
on conflict (id) do update
set public=false,
    file_size_limit=20971520,
    allowed_mime_types=excluded.allowed_mime_types;
